language: python 

python: 

  - "3.7"

services:

  - mysql

install: 

  - pip install -r requirements.txt
before_script: 

  - mysql -e 'create database test;' -u root
script: 
  - python Electionportal/manage.py makemigrations accounts
  - python Electionportal/manage.py makemigrations Election
  - python Electionportal/manage.py makemigrations application
  - python Electionportal/manage.py migrate accounts
  - python Electionportal/manage.py migrate Election
  - python Electionportal/manage.py migrate application
  
  
  - python Electionportal/manage.py test application
