# Generated by Django 3.1.7 on 2021-03-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('allowed_depts', models.ManyToManyField(to='accounts.Department')),
                ('allowed_years', models.ManyToManyField(to='accounts.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=1000)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Votesreceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.election')),
            ],
        ),
        migrations.CreateModel(
            name='Votescasted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.voter')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='application_win',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_timestamp', to='Election.timestamp'),
        ),
        migrations.AddField(
            model_name='election',
            name='voting_win',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voting_timestamp', to='Election.timestamp'),
        ),
    ]
